# Clasificacacion con KNN

In [35]:
import numpy as np
# lo ocupamos para el algoritmo clasificador
import sklearn 
# vemos el dataset de iris
from sklearn.datasets import load_iris
# lo ocupamos para dividir nuestro data en test de entrenamiento y de prueba
from sklearn.model_selection import train_test_split

In [7]:
# creamos una variable llamda iris, en la cual traemos todo el set de datos
iris = load_iris()

In [8]:
# El tipo de dato por lo regular viene en un formato Bunch que es un tipo de diccionario
type(iris)

sklearn.utils.Bunch

In [9]:
# vemos las llaves de nuestro data set
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [10]:
# vemos que hay en la llave data (vemos una matriz con cuatro dimensiones de las mediciones, 
#cada fila es una flor y cada columna es una medicion)
iris["data"]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
# nombres de las posiblesclasificaciones
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
# en la llave de target  tenemos las etiquetas correspondientes a cada una de los renglones del data 
#(0=setosa, 1=versicolor, 2=virginica)
iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# los nombres de cada una de las mediciones o columnas de la data
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
#Ocupamos la funcion de test_train_splitpara separar nuestra data en set de entrenamiento y testing
#los parametros que recibe la funcion son las caracteristicas o data y las etiquetas o target y nos regresa cuatro valores
#x para test y train y Y para test y train

X_train, X_test, y_train, y_test = train_test_split (iris["data"],iris["target"])

In [30]:
#vemos la forma que tienen nuestras variables X y Y para entrenar 
#(x es una matriz de 112 por 4 osea 112 flores con sus mediciones)
X_train.shape

(112, 4)

In [31]:
#es un vector de 112, que son las etiquetas corrsponedientes a cada elemento de X osea cada una de las clasificaciones
y_train.shape

(112,)

In [38]:
# AQUI VIENE LO BUENO. IMPORTAMOS DE SKLEARN NUESTRO CLASIFICADOR, ESTAREMOS OCUPANDO KNEIGHTBORS
#K ES IGUAL AL NUMERO DE VECINOS QUE ESTEMOS CONSIDERANDO
from sklearn.neighbors import KNeighborsClassifier

In [54]:
#Asignamos  a nuestra variable knn nuestro nuevo clasificador y le decimos que considere k=7 osea los 7 vecinos mas cercanos
knn = KNeighborsClassifier(n_neighbors = 25)

In [55]:
# en nuestra misma variable de knn ocuapremos la funcion fit que sirve para entrenarlo y los parametros que recibe son
#los datos de X_train y y_train que obtuvimos del train_test_split
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=25)

In [56]:
# .score nos sirve para ver  que tan bien aprendio nuestro algoritmo, los parametros que recibe son
#X y Y de test
knn.score(X_test, y_test)

0.9473684210526315

In [63]:
# queremos predecir 4 medicionesy queremos que nos diga a que clasificacion pertenece,
#para ello ocupamos la funcion predit sobre knn y le damos nuestras medidad
knn.predict([[8, 0.2, .03, 9]])

#nos dice que pertenece al elemento numero 2 de nuestro arreglo

array([2])

In [58]:
# Si vemos los nombres de las etiquetas vemos a que familia pertenece
iris.target_names
#vemos que pertenece a versicolor

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')